Repository Winter-Seminar-Series/WSS-site, pull requests merged in 2023-03, with the labels that each got.

#356 Fix section padding and header size
  front/public/css/style.css
Labels: enhancement, frontend

#360 Fix birth date format
  front/src/components/Form.tsx
Labels: bug, frontend

#366 Fix datepicker crash + add validation
  front/src/components/Form.tsx
Labels: frontend
